pipeline:
  identifier: Build_Cager2808_sample_harness_1704358794361
  name: Build sample-harness
  orgIdentifier: default
  projectIdentifier: new_demo5
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Cager2808/sample-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    shell: Sh
                    command: |
                      npm install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: sfdx install
                  identifier: sfdx_install
                  spec:
                    shell: Bash
                    command: |-
                      npm install --global sfdx-cli
                      sfdx --version
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
