pipeline:
  identifier: Build_Cager2808_sample_harness_1704280733742
  name: Build sample-harness
  orgIdentifier: default
  projectIdentifier: Salesforce_harness_app
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698735122136
        repoName: Cager2808/sample-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - stepGroup:
                  name: Pre_requisite
                  identifier: Pre_requisite
                  steps:
                    - parallel:
                        - step:
                            type: Run
                            name: npm_install_and_sfdx_cli
                            identifier: npm_install_and_sfdx_cli
                            spec:
                              shell: Bash
                              command: npm install --global sfdx-cli@$2.19.8
                        - step:
                            type: Run
                            name: npm_install_sfdx_git
                            identifier: npm_install_sfdx_git
                            spec:
                              shell: Bash
                              command: sudo npm install sfdx-git-delta@^4.x.x -g
              - step:
                  type: Run
                  name: Git_Diff_Check
                  identifier: Git_Diff_Check
                  spec:
                    shell: Bash
                    command: |2
                       git --version
                       git clone 'https://github.com/Cager2808/Salesforce-demo'
                       ls -alrt
                      cd 'Salesforce-demo'
                      git branch
                      git diff --diff-filter=ACMRT HEAD^ HEAD
                      ls -alrt
                      sgd --to HEAD --from HEAD^ --repo . --output .
                      ls -lart
                      echo "package xml"
                      cat package/package.xml
                      echo "Display contents of Destructive changes xml"
                      cat destructiveChanges/destructiveChanges.xml
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
