pipeline:
  identifier: Build_Cager2808_sample_harness_1704280733742
  name: Build sample-harness
  orgIdentifier: default
  projectIdentifier: Salesforce_harness_app
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698735122136
        repoName: Cager2808/sample-harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest1
                  name: npm_test
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
